### ISSUE TITLE
defase error

### ISSUE THREAD

**Issue by gerardocastro** [spree-contrib/spree_rdr_theme#7]
Hi, im trying to install the theme but im getting this error:
replace_shipping_method.rb:1: uninitialized constant Deface (NameError)
any help?? please.

**Comment by JDutil** [comment]
Which version of spree are you using?  Have you tried adding the deface gem to your gemfile?  Depending on your version of spree you will also need the deface gem. If the version of spree that your using is older than the version which requires deface than you may not be able to use this theme.

**Comment by gerardocastro** [comment]
i downloaded the example and it worked but do u know how can i remove the s3 configuration?

**Comment by JDutil** [comment]
The spree demo code?  You can remove the aws-s3 gem and its related files under config/s3.yml and config/initializers/s3.rb, but there are likely other references to s3 as well.  I'm not entirely sure of them all since I start with a fresh app, but you should be able to do a project wide find of s3 and make updates where necessary.

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
